# Generated by Django 5.1.3 on 2024-12-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
